### ISSUE TITLE
刚下载发现一些问题

### ISSUE THREAD

**Issue by q121330959** [CatImmortal/Trinity#1]
GameFramework预制件有些丢失了。代码运行到 
type = GameEntry.ILRuntime.AppDomain.LoadedTypes[hotfixUGuiFormFullName];
就报错了
Open UI form failure, asset name 'Assets/GameMain/UI/UIForms/TestForm.prefab', UI group name 'UITest', pause covered UI form 'False', error message 'System.NullReferenceException: Object reference not set to an instance of an object
  at Trinity.HotfixUGuiForm.OnInit (System.Object userData) [0x00028] in

估计是没有获取到C#里面的DLL文件

**Comment by 838728713** [comment]
大佬
